  CREATE TABLE "ACTIONS" 
   (	"ACTION" VARCHAR2(20 CHAR) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP", 
	 CONSTRAINT "ACTIONS_PK" PRIMARY KEY ("ACTION")
  USING INDEX  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;