  CREATE TABLE "ACTIONS" 
   (	"ACTION" VARCHAR2(20 CHAR) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(255 CHAR), 
	"CREATE_DATE" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	 CONSTRAINT "ACTIONS_PK" PRIMARY KEY ("ACTION")
  USING INDEX  ENABLE
   ) ;

  CREATE OR REPLACE EDITIONABLE TRIGGER "ACTIONS_CREATE_DATE" 
before
insert on "ACTIONS"
for each row
begin
    :NEW.CREATE_DATE := SYSDATE;
end;
/
ALTER TRIGGER "ACTIONS_CREATE_DATE" ENABLE;