create table book_genres (
    id                             number generated by default on null as identity 
                                   constraint book_genres_id_pk primary key,
    name                           varchar2(200 char)
)
;