-- create tables
create table books (
    id                             number generated by default on null as identity 
                                   constraint books_id_pk primary key,
    title                          varchar2(200 char),
    author                         varchar2(200 char),
    isbn                           varchar2(13 char),
    year                           number,
    genre_id                       number
                                   constraint books_genre_id_fk
                                   references book_genres on delete cascade,
    location_id                    number
                                   constraint books_location_id_fk
                                   references locations on delete cascade,
    score                          number,
    description                    varchar2(4000 char),
    cover                          blob
)
;

-- table index
create index books_i1 on books (genre_id);
create index books_i42 on books (location_id);
