create table locations (
    id                             number generated by default on null as identity 
                                   constraint locations_id_pk primary key,
    name                           varchar2(200 char)
)
;