  CREATE TABLE "SECTIONS" 
   (	"SECTION" VARCHAR2(30 CHAR) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(100 CHAR), 
	"CREATE_DATE" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	 CONSTRAINT "SECTIONS_PK" PRIMARY KEY ("SECTION")
  USING INDEX  ENABLE
   ) ;

  CREATE OR REPLACE EDITIONABLE TRIGGER "SECTIONS_CREATE_DATE" 
before
insert on "SECTIONS"
for each row
begin
    :NEW.CREATE_DATE := SYSDATE;
end;
/
ALTER TRIGGER "SECTIONS_CREATE_DATE" ENABLE;